server:
  forward-headers-strategy: native
spring:
  application:
    name: back
  config:
   import: optional:file:.env[.properties]
  profiles:
    active: dev
    include: secret
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      auto-commit: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${SPRING__SECURITY__OAUTH2__CLIENT__REGISTRATION_KAKAO_CLIENT_ID}
            scope: profile_nickname, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
          google:
            client-id: ${SPRING__SECURITY__OAUTH2__CLIENT__REGISTRATION_GOOGLE_CLIENT_ID}
            client-secret: ${SPRING__SECURITY__OAUTH2__CLIENT__REGISTRATION_GOOGLE_CLIENT_SECRET}
            scope: profile
            client-name: Google
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
          naver:
            client-id: ${SPRING__SECURITY__OAUTH2__CLIENT__REGISTRATION_NAVER_CLIENT_ID}
            client-secret: ${SPRING__SECURITY__OAUTH2__CLIENT__REGISTRATION_NAVER_CLIENT_SECRET}
            scope: profile_nickname, profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.back: DEBUG
custom:
  jwt:
      secretKey: ${CUSTOM__JWT__SECRET_KEY}
  accessToken:
    expireSeconds: "#{60 * 10}"
  notProdMembers:
    - username: KAKAO__123132423
      apiKey: kakao__1
      nickname: 카카오소셜회원
      profileImgUrl: https://picsum.photos/300/300
    - username: GOOGLE__1123123123213132
      apiKey: google__1
      nickname: 구글소셜회원
      profileImgUrl: https://picsum.photos/300/300
    - username: NAVER__xzccxcqw123123
      apiKey: naver__1
      nickname: 네이버소셜회원
      profileImgUrl: https://picsum.photos/300/300